@startuml
!theme metal
'skinparam BackgroundColor #333333
'skinparam LineType ortho
skinparam Arrow {
  Color #F0FFFF
  FontColor #F0FFFF
}
skinparam Class {
  BackgroundColor #444444
  BorderColor #F0FFFF
  FontColor #F0FFFF
}
hide circle
hide members
left to right direction

class BatchContent
class EnvelopeSpecName
'class EnvironmentTag #line.dashed
class Partition #line.dashed
class ProcessActivityId #line.dashed
class MessagingStepActivityIds #line.dashed
class Parts
class Any


BatchContent -- EnvelopeSpecName
'BatchContent -- EnvironmentTag
BatchContent -- Partition
BatchContent -- ProcessActivityId
BatchContent -- MessagingStepActivityIds
BatchContent -- Parts
Parts -- Any : 1..*

@enduml