@startuml
!theme metal
'skinparam BackgroundColor #333333
'skinparam LineType ortho
skinparam NodeSep 7
skinparam Arrow {
  Color #F0FFFF
  FontColor #F0FFFF
}
skinparam Component {
  BackgroundColor #444444
  BorderColor #F0FFFF
  FontColor #F0FFFF
}
[Be.Stateless.BizTalk.Transform.ExtensionObjects] as BizTalk.ExtensionObjects
[Be.Stateless.Extensions] as Extensions
[Be.Stateless.Reflection] as Reflection
[Be.Stateless.Runtime] as Runtime
    Runtime .u.> Extensions
[Be.Stateless.BizTalk.Settings] as BizTalk.Settings
    BizTalk.Settings .u.> Extensions
    BizTalk.Settings .u.> Runtime
[Be.Stateless.Security] as Security
    Security .u.> Extensions
[Be.Stateless.Stream] as Stream
    Stream .u.> Extensions
[Be.Stateless.Xml] as Xml
    Xml .u.> Extensions
    Xml .u.> Reflection
    Xml .u.> Stream
[Be.Stateless.BizTalk.Abstractions] as BizTalk.Abstractions
    BizTalk.Abstractions .u.> Extensions
[Be.Stateless.BizTalk.Xml] as BizTalk.Xml
    BizTalk.Xml .u.> Extensions
    BizTalk.Xml .u.> Runtime
    BizTalk.Xml .u.> Xml
[Be.Stateless.BizTalk.Stream] as BizTalk.Stream
    BizTalk.Stream .u.> BizTalk.Xml
    BizTalk.Stream .u.> Extensions
    BizTalk.Stream .u.> Runtime
    BizTalk.Stream .u.> Stream
    BizTalk.Stream .u.> Xml
[Be.Stateless.BizTalk.XLang] as BizTalk.XLang
    BizTalk.XLang .u.> BizTalk.Abstractions
    BizTalk.XLang .u.> BizTalk.Xml
    BizTalk.XLang .u.> Extensions
    BizTalk.XLang .u.> Reflection
    BizTalk.XLang .u.> Runtime
    BizTalk.XLang .u.> Xml
[Be.Stateless.BizTalk.Messaging] as BizTalk.Messaging
    BizTalk.Messaging .u.> BizTalk.Abstractions
    BizTalk.Messaging .u.> BizTalk.Stream
    BizTalk.Messaging .u.> BizTalk.Xml
    BizTalk.Messaging .u.> Extensions
    BizTalk.Messaging .u.> Runtime
    BizTalk.Messaging .u.> Xml
[Be.Stateless.BizTalk.ServiceModel] as BizTalk.ServiceModel
    BizTalk.ServiceModel .u.> BizTalk.Abstractions
    BizTalk.ServiceModel .u.> BizTalk.Messaging
    BizTalk.ServiceModel .u.> BizTalk.Stream
    BizTalk.ServiceModel .u.> BizTalk.Xml
    BizTalk.ServiceModel .u.> Extensions
    BizTalk.ServiceModel .u.> Runtime
    BizTalk.ServiceModel .u.> Stream
    BizTalk.ServiceModel .u.> Xml
[Be.Stateless.BizTalk.Pipeline.MicroComponents] as BizTalk.MicroComponents
    BizTalk.MicroComponents .u.> BizTalk.Abstractions
    BizTalk.MicroComponents .u.> BizTalk.Messaging
    BizTalk.MicroComponents .u.> BizTalk.Stream
    BizTalk.MicroComponents .u.> BizTalk.Xml
    BizTalk.MicroComponents .u.> Extensions
    BizTalk.MicroComponents .u.> Security
    BizTalk.MicroComponents .u.> Stream
    BizTalk.MicroComponents .u.> Xml
[Be.Stateless.BizTalk.Factory.Logging] as BizTalk.Factory.Logging
    BizTalk.Factory.Logging .u.> Runtime
@enduml
